deploy:
  needs: build-and-test
  runs-on: ubuntu-latest

  steps:
  - name: Set up SSH Key
    run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ci-cd-key
      chmod 600 ~/.ssh/ci-cd-key
      ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

  - name: Deploy to AWS EC2
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd ~/node-ci-cd-3 || git clone https://github.com/Joy-it-code/node-ci-cd-3.git ~/node-ci-cd-3
        cd ~/node-ci-cd-3
        git pull origin main
        npm install
        pm2 restart index.js || pm2 start index.js --name "node-app"
